# Generated by Django 4.2 on 2025-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='备份名称')),
                ('description', models.TextField(blank=True, verbose_name='备份描述')),
                ('status', models.CharField(choices=[('pending', '待备份'), ('running', '备份中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='备份文件路径')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '数据备份',
                'verbose_name_plural': '数据备份',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='分享令牌')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='访问密码')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('max_downloads', models.PositiveIntegerField(default=0, verbose_name='最大下载次数')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='已下载次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分享链接',
                'verbose_name_plural': '分享链接',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, verbose_name='配置描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', '调试'), ('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误'), ('CRITICAL', '严重')], max_length=10, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='模块')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
