# Generated by Django 4.2 on 2025-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文档标题')),
                ('description', models.TextField(blank=True, verbose_name='文档描述')),
                ('file', models.FileField(upload_to='media/user_files/%Y/%m/%d/', verbose_name='文档文件')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=20, verbose_name='文件类型')),
                ('file_hash', models.CharField(max_length=64, unique=True, verbose_name='文件哈希值')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('review', '待审核'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_starred', models.BooleanField(default=False, verbose_name='是否星标')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标标识')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文档分类',
                'verbose_name_plural': '文档分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('download', '下载'), ('view', '查看'), ('star', '星标'), ('archive', '归档'), ('publish', '发布')], max_length=20, verbose_name='操作类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作IP')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='操作详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '文档操作日志',
                'verbose_name_plural': '文档操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10, verbose_name='版本号')),
                ('file', models.FileField(upload_to='media/user_files/versions/%Y/%m/%d/', verbose_name='版本文件')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('change_log', models.TextField(blank=True, verbose_name='更新日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文档版本',
                'verbose_name_plural': '文档版本',
                'ordering': ['-created_at'],
            },
        ),
    ]
