# Generated by Django 4.2 on 2025-10-17 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='关联文档'),
        ),
        migrations.AddField(
            model_name='documentoperationlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='documents.document', verbose_name='关联文档'),
        ),
        migrations.AddField(
            model_name='documentoperationlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='documents.documentcategory', verbose_name='父分类'),
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_documents', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='所属分类'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='documentoperationlog',
            index=models.Index(fields=['user', 'operation'], name='documents_d_user_id_d70aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoperationlog',
            index=models.Index(fields=['document', 'created_at'], name='documents_d_documen_0d0b80_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['author', 'status'], name='documents_d_author__c15f80_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'status'], name='documents_d_categor_0ec696_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_public', 'status'], name='documents_d_is_publ_78cb69_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
    ]
